CREATE TABLE IF NOT EXISTS classes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE,
  grade INTEGER,
  is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT,
  name TEXT,
  score_delta INTEGER
);

CREATE TABLE IF NOT EXISTS admins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE,
  password TEXT
);

CREATE TABLE IF NOT EXISTS schedule_weeks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_number INTEGER,
  start_date TEXT,
  end_date TEXT,
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id INTEGER UNIQUE,
  password_gvcn TEXT,
  password_bcs TEXT,
  password_codo TEXT,
  pin_bcs TEXT,
  pin_failed_attempts INTEGER DEFAULT 0,
  pin_locked_until BIGINT DEFAULT 0,
  password_changed INTEGER DEFAULT 0,
  created_at TEXT,
  password_changed_gvcn INTEGER DEFAULT 0,
  password_changed_bcs INTEGER DEFAULT 0,
  password_changed_codo INTEGER DEFAULT 0,
  CONSTRAINT fk_accounts_class_id FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS schedule_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_id INTEGER NOT NULL,
  red_class TEXT NOT NULL,
  duty_class TEXT NOT NULL,
  CONSTRAINT fk_schedule_assignments_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE,
  CONSTRAINT fk_schedule_assignments_red_class FOREIGN KEY (red_class) REFERENCES classes(name) ON DELETE CASCADE,
  CONSTRAINT fk_schedule_assignments_duty_class FOREIGN KEY (duty_class) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS duty_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_id INTEGER NOT NULL,
  date TEXT,
  red_class TEXT NOT NULL,
  duty_class TEXT NOT NULL,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'signed')),
  created_at TEXT,
  signed_at TEXT,
  signed_snapshot_hash TEXT,
  CONSTRAINT fk_duty_sessions_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE,
  CONSTRAINT fk_duty_sessions_red_class FOREIGN KEY (red_class) REFERENCES classes(name) ON DELETE CASCADE,
  CONSTRAINT fk_duty_sessions_duty_class FOREIGN KEY (duty_class) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS duty_violations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  rule_id INTEGER NOT NULL,
  quantity INTEGER,
  note TEXT,
  CONSTRAINT fk_duty_violations_session_id FOREIGN KEY (session_id) REFERENCES duty_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_duty_violations_rule_id FOREIGN KEY (rule_id) REFERENCES rules(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS duty_signatures (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  photo_path TEXT,
  signed_at TEXT,
  CONSTRAINT fk_duty_signatures_session_id FOREIGN KEY (session_id) REFERENCES duty_sessions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS duty_revision_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  action TEXT,
  created_at TEXT,
  CONSTRAINT fk_duty_revision_logs_session_id FOREIGN KEY (session_id) REFERENCES duty_sessions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS week_closings (
  week_id INTEGER PRIMARY KEY,
  closed_at TEXT,
  CONSTRAINT fk_week_closings_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS daily_bonus (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER,
  week_id INTEGER,
  date TEXT,
  class_name TEXT,
  points DOUBLE PRECISION,
  min_score DOUBLE PRECISION,
  all_above_9 INTEGER,
  source TEXT,
  created_at TEXT,
  updated_at TEXT,
  periods_json TEXT,
  CONSTRAINT uq_daily_bonus_week_date_class UNIQUE (week_id, date, class_name),
  CONSTRAINT fk_daily_bonus_session_id FOREIGN KEY (session_id) REFERENCES duty_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_daily_bonus_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE,
  CONSTRAINT fk_daily_bonus_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bonus_uploads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_id INTEGER,
  grade TEXT,
  file_name TEXT,
  xlsx_count INTEGER,
  uploaded_at TEXT,
  CONSTRAINT fk_bonus_uploads_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS timetables (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  effective_date TEXT,
  file_name TEXT,
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS timetable_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timetable_id INTEGER NOT NULL,
  class_name TEXT NOT NULL,
  day_of_week INTEGER NOT NULL,
  session TEXT NOT NULL,
  period INTEGER NOT NULL,
  subject TEXT,
  CONSTRAINT fk_timetable_entries_timetable_id FOREIGN KEY (timetable_id) REFERENCES timetables(id) ON DELETE CASCADE,
  CONSTRAINT fk_timetable_entries_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weekly_scores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_id INTEGER NOT NULL,
  class_name TEXT NOT NULL,
  score DOUBLE PRECISION,
  updated_at TEXT,
  CONSTRAINT fk_weekly_scores_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE,
  CONSTRAINT fk_weekly_scores_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weekly_bonus (
  week_id INTEGER,
  class_name TEXT,
  points DOUBLE PRECISION,
  reason TEXT,
  created_at TEXT,
  updated_at TEXT,
  PRIMARY KEY (week_id, class_name),
  CONSTRAINT fk_weekly_bonus_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE,
  CONSTRAINT fk_weekly_bonus_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS month_summaries (
  month_key TEXT PRIMARY KEY,
  week_ids TEXT,
  closed_at TEXT,
  created_at TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS month_adjustments (
  month_key TEXT,
  class_name TEXT,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  reason TEXT,
  created_at TEXT,
  updated_at TEXT,
  PRIMARY KEY (month_key, class_name),
  CONSTRAINT fk_month_adjustments_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS month_scores (
  month_key TEXT,
  class_name TEXT,
  grade INTEGER,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  total_score DOUBLE PRECISION,
  rank INTEGER,
  note TEXT,
  updated_at TEXT,
  PRIMARY KEY (month_key, class_name),
  CONSTRAINT fk_month_scores_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS semester_summaries (
  semester_key TEXT PRIMARY KEY,
  week_ids TEXT,
  closed_at TEXT,
  created_at TEXT,
  updated_at TEXT,
  month_keys TEXT
);

CREATE TABLE IF NOT EXISTS semester_adjustments (
  semester_key TEXT,
  class_name TEXT,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  reason TEXT,
  created_at TEXT,
  updated_at TEXT,
  PRIMARY KEY (semester_key, class_name),
  CONSTRAINT fk_semester_adjustments_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS semester_scores (
  semester_key TEXT,
  class_name TEXT,
  grade INTEGER,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  total_score DOUBLE PRECISION,
  rank INTEGER,
  note TEXT,
  updated_at TEXT,
  PRIMARY KEY (semester_key, class_name),
  CONSTRAINT fk_semester_scores_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS year_summaries (
  year_key TEXT PRIMARY KEY,
  week_ids TEXT,
  closed_at TEXT,
  created_at TEXT,
  updated_at TEXT,
  semester_keys TEXT
);

CREATE TABLE IF NOT EXISTS year_adjustments (
  year_key TEXT,
  class_name TEXT,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  reason TEXT,
  created_at TEXT,
  updated_at TEXT,
  PRIMARY KEY (year_key, class_name),
  CONSTRAINT fk_year_adjustments_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS year_scores (
  year_key TEXT,
  class_name TEXT,
  grade INTEGER,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  total_score DOUBLE PRECISION,
  rank INTEGER,
  note TEXT,
  updated_at TEXT,
  PRIMARY KEY (year_key, class_name),
  CONSTRAINT fk_year_scores_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

ALTER TABLE accounts ADD COLUMN IF NOT EXISTS password_changed INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS password_changed_gvcn INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS password_changed_bcs INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS password_changed_codo INTEGER DEFAULT 0;

ALTER TABLE daily_bonus ADD COLUMN IF NOT EXISTS min_score DOUBLE PRECISION;
ALTER TABLE daily_bonus ADD COLUMN IF NOT EXISTS all_above_9 INTEGER;
ALTER TABLE daily_bonus ADD COLUMN IF NOT EXISTS session_id INTEGER;
ALTER TABLE daily_bonus ADD COLUMN IF NOT EXISTS periods_json TEXT;
ALTER TABLE weekly_scores ALTER COLUMN score TYPE DOUBLE PRECISION USING score::double precision;

ALTER TABLE semester_summaries ADD COLUMN IF NOT EXISTS month_keys TEXT;
ALTER TABLE year_summaries ADD COLUMN IF NOT EXISTS semester_keys TEXT;
ALTER TABLE duty_sessions ADD COLUMN IF NOT EXISTS signed_snapshot_hash TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS uq_duty_sessions_week_date_red ON duty_sessions(week_id, date, red_class);
CREATE INDEX IF NOT EXISTS idx_schedule_assignments_week ON schedule_assignments(week_id);
CREATE INDEX IF NOT EXISTS idx_duty_sessions_week_date ON duty_sessions(week_id, date);
CREATE INDEX IF NOT EXISTS idx_duty_sessions_red ON duty_sessions(red_class);
CREATE INDEX IF NOT EXISTS idx_duty_sessions_duty ON duty_sessions(duty_class);
CREATE INDEX IF NOT EXISTS idx_duty_violations_session ON duty_violations(session_id);
CREATE INDEX IF NOT EXISTS idx_duty_violations_rule ON duty_violations(rule_id);
CREATE INDEX IF NOT EXISTS idx_duty_signatures_session ON duty_signatures(session_id);
CREATE INDEX IF NOT EXISTS idx_duty_revision_logs_session ON duty_revision_logs(session_id);
CREATE INDEX IF NOT EXISTS idx_daily_bonus_session ON daily_bonus(session_id);
CREATE INDEX IF NOT EXISTS idx_bonus_uploads_week_grade ON bonus_uploads(week_id, grade);
CREATE INDEX IF NOT EXISTS idx_timetable_entries ON timetable_entries(timetable_id, class_name, day_of_week, session, period);
