CREATE TABLE IF NOT EXISTS classes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE,
  grade INTEGER,
  is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT,
  name TEXT,
  score_delta INTEGER
);

CREATE TABLE IF NOT EXISTS admins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE,
  password TEXT
);

CREATE TABLE IF NOT EXISTS system_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key TEXT UNIQUE,
  setting_value TEXT,
  description TEXT,
  updated_at TEXT,
  updated_by TEXT
);

CREATE TABLE IF NOT EXISTS ai_settings (
  id INTEGER PRIMARY KEY,
  provider TEXT,
  api_key TEXT,
  base_url TEXT,
  model TEXT,
  temperature DOUBLE PRECISION DEFAULT 0,
  updated_at TEXT,
  updated_by TEXT
);

CREATE TABLE IF NOT EXISTS school_years (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  start_year INTEGER NOT NULL,
  end_year INTEGER NOT NULL,
  created_at TEXT,
  CONSTRAINT chk_school_year_range CHECK (end_year = start_year + 1)
);

CREATE TABLE IF NOT EXISTS semesters (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_year_id INTEGER NOT NULL,
  semester_number INTEGER NOT NULL,
  name TEXT NOT NULL,
  created_at TEXT,
  CONSTRAINT uq_semesters_year_number UNIQUE (school_year_id, semester_number),
  CONSTRAINT chk_semester_number CHECK (semester_number BETWEEN 1 AND 9),
  CONSTRAINT fk_semesters_school_year_id FOREIGN KEY (school_year_id) REFERENCES school_years(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS months (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id INTEGER NOT NULL,
  month_number INTEGER NOT NULL,
  month_key TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  created_at TEXT,
  CONSTRAINT uq_months_semester_number UNIQUE (semester_id, month_number),
  CONSTRAINT chk_month_number CHECK (month_number BETWEEN 1 AND 12),
  CONSTRAINT fk_months_semester_id FOREIGN KEY (semester_id) REFERENCES semesters(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS schedule_weeks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month_id INTEGER,
  week_number INTEGER,
  start_date TEXT,
  end_date TEXT,
  created_at TEXT,
  CONSTRAINT fk_schedule_weeks_month_id FOREIGN KEY (month_id) REFERENCES months(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id INTEGER UNIQUE,
  password_gvcn TEXT,
  password_ban_can_su TEXT,
  password_codo TEXT,
  pin_ban_can_su TEXT,
  pin_failed_attempts INTEGER DEFAULT 0,
  pin_locked_until BIGINT DEFAULT 0,
  password_changed INTEGER DEFAULT 0,
  created_at TEXT,
  password_changed_gvcn INTEGER DEFAULT 0,
  password_changed_ban_can_su INTEGER DEFAULT 0,
  password_changed_codo INTEGER DEFAULT 0,
  CONSTRAINT fk_accounts_class_id FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_passkeys (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  credential_id TEXT NOT NULL UNIQUE,
  public_key BYTEA NOT NULL,
  counter BIGINT NOT NULL DEFAULT 0,
  device_name TEXT NOT NULL DEFAULT 'Thiết bị không xác định',
  transports TEXT NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_user_passkeys_user_id ON user_passkeys (user_id);

CREATE TABLE IF NOT EXISTS schedule_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_id INTEGER NOT NULL,
  red_class TEXT NOT NULL,
  duty_class TEXT NOT NULL,
  CONSTRAINT fk_schedule_assignments_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE,
  CONSTRAINT fk_schedule_assignments_red_class FOREIGN KEY (red_class) REFERENCES classes(name) ON DELETE CASCADE,
  CONSTRAINT fk_schedule_assignments_duty_class FOREIGN KEY (duty_class) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS duty_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_id INTEGER NOT NULL,
  date TEXT,
  red_class TEXT NOT NULL,
  duty_class TEXT NOT NULL,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'signed')),
  created_at TEXT,
  signed_at TEXT,
  signed_snapshot_hash TEXT,
  CONSTRAINT fk_duty_sessions_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE,
  CONSTRAINT fk_duty_sessions_red_class FOREIGN KEY (red_class) REFERENCES classes(name) ON DELETE CASCADE,
  CONSTRAINT fk_duty_sessions_duty_class FOREIGN KEY (duty_class) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS duty_violations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  rule_id INTEGER NOT NULL,
  quantity INTEGER,
  note TEXT,
  CONSTRAINT fk_duty_violations_session_id FOREIGN KEY (session_id) REFERENCES duty_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_duty_violations_rule_id FOREIGN KEY (rule_id) REFERENCES rules(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS duty_signatures (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  photo_path TEXT,
  signed_at TEXT,
  CONSTRAINT fk_duty_signatures_session_id FOREIGN KEY (session_id) REFERENCES duty_sessions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS duty_revision_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  action TEXT,
  created_at TEXT,
  CONSTRAINT fk_duty_revision_logs_session_id FOREIGN KEY (session_id) REFERENCES duty_sessions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS week_closings (
  week_id INTEGER PRIMARY KEY,
  closed_at TEXT,
  CONSTRAINT fk_week_closings_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS daily_bonus (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER,
  week_id INTEGER,
  date TEXT,
  class_name TEXT,
  points DOUBLE PRECISION,
  min_score DOUBLE PRECISION,
  all_above_9 INTEGER,
  source TEXT,
  created_at TEXT,
  updated_at TEXT,
  periods_json TEXT,
  CONSTRAINT uq_daily_bonus_week_date_class UNIQUE (week_id, date, class_name),
  CONSTRAINT fk_daily_bonus_session_id FOREIGN KEY (session_id) REFERENCES duty_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_daily_bonus_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE,
  CONSTRAINT fk_daily_bonus_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bonus_uploads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_id INTEGER,
  grade TEXT,
  file_name TEXT,
  xlsx_count INTEGER,
  uploaded_at TEXT,
  CONSTRAINT fk_bonus_uploads_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS support_tickets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_role TEXT NOT NULL CHECK (creator_role IN ('gvcn', 'ban_can_su', 'co_do')),
  creator_class_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  request_type TEXT NOT NULL CHECK (request_type IN ('duty_complaint', 'system_bug', 'suggestion', 'usage_support', 'other')),
  status TEXT NOT NULL DEFAULT 'in_progress' CONSTRAINT chk_support_ticket_status CHECK (status IN ('in_progress', 'resolved')),
  linked_week_id INTEGER,
  linked_duty_session_id INTEGER,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CONSTRAINT fk_support_tickets_creator_class FOREIGN KEY (creator_class_id) REFERENCES classes(id) ON DELETE RESTRICT,
  CONSTRAINT fk_support_tickets_week FOREIGN KEY (linked_week_id) REFERENCES schedule_weeks(id) ON DELETE SET NULL,
  CONSTRAINT fk_support_tickets_duty_session FOREIGN KEY (linked_duty_session_id) REFERENCES duty_sessions(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS support_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id INTEGER NOT NULL,
  sender_role TEXT NOT NULL CHECK (sender_role IN ('admin', 'gvcn', 'ban_can_su', 'co_do')),
  sender_class_id INTEGER,
  body TEXT NOT NULL,
  created_at TEXT NOT NULL,
  CONSTRAINT fk_support_messages_ticket FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE,
  CONSTRAINT fk_support_messages_sender_class FOREIGN KEY (sender_class_id) REFERENCES classes(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS support_attachments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id INTEGER NOT NULL,
  file_path TEXT NOT NULL,
  file_name TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  CONSTRAINT fk_support_attachments_message FOREIGN KEY (message_id) REFERENCES support_messages(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS support_notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id INTEGER NOT NULL,
  message_id INTEGER,
  recipient_role TEXT NOT NULL CHECK (recipient_role IN ('admin', 'gvcn', 'ban_can_su', 'co_do')),
  recipient_class_id INTEGER,
  is_read INTEGER NOT NULL DEFAULT 0 CHECK (is_read IN (0, 1)),
  created_at TEXT NOT NULL,
  CONSTRAINT fk_support_notifications_ticket FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE,
  CONSTRAINT fk_support_notifications_message FOREIGN KEY (message_id) REFERENCES support_messages(id) ON DELETE CASCADE,
  CONSTRAINT fk_support_notifications_recipient_class FOREIGN KEY (recipient_class_id) REFERENCES classes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS absence_evidences (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id INTEGER NOT NULL,
  student_name TEXT NOT NULL,
  week_id INTEGER NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  note TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  submitted_by TEXT NOT NULL,
  submitted_at TEXT NOT NULL,
  reviewed_by TEXT,
  reviewed_at TEXT,
  review_reason TEXT,
  approved_exemption_count INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_absence_evidence_range CHECK (start_date <= end_date),
  CONSTRAINT fk_absence_evidences_class_id FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
  CONSTRAINT fk_absence_evidences_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS absence_evidence_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evidence_id INTEGER NOT NULL,
  file_url TEXT NOT NULL,
  file_name TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_absence_evidence_files_evidence_id FOREIGN KEY (evidence_id) REFERENCES absence_evidences(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS absence_exemption_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evidence_id INTEGER NOT NULL,
  duty_session_id INTEGER NOT NULL,
  duty_violation_id INTEGER NOT NULL,
  absence_type TEXT NOT NULL,
  approved_quantity INTEGER NOT NULL CHECK (approved_quantity > 0),
  created_at TEXT NOT NULL,
  CONSTRAINT fk_absence_exemption_logs_evidence_id FOREIGN KEY (evidence_id) REFERENCES absence_evidences(id) ON DELETE CASCADE,
  CONSTRAINT fk_absence_exemption_logs_duty_session_id FOREIGN KEY (duty_session_id) REFERENCES duty_sessions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_absence_exemption_logs_duty_violation_id FOREIGN KEY (duty_violation_id) REFERENCES duty_violations(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS timetables (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  effective_date TEXT,
  file_name TEXT,
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS timetable_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timetable_id INTEGER NOT NULL,
  class_name TEXT NOT NULL,
  day_of_week INTEGER NOT NULL,
  session TEXT NOT NULL,
  period INTEGER NOT NULL,
  subject TEXT,
  CONSTRAINT fk_timetable_entries_timetable_id FOREIGN KEY (timetable_id) REFERENCES timetables(id) ON DELETE CASCADE,
  CONSTRAINT fk_timetable_entries_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weekly_scores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_id INTEGER NOT NULL,
  class_name TEXT NOT NULL,
  score DOUBLE PRECISION,
  updated_at TEXT,
  CONSTRAINT fk_weekly_scores_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE,
  CONSTRAINT fk_weekly_scores_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weekly_bonus (
  week_id INTEGER,
  class_name TEXT,
  points DOUBLE PRECISION,
  reason TEXT,
  created_at TEXT,
  updated_at TEXT,
  PRIMARY KEY (week_id, class_name),
  CONSTRAINT fk_weekly_bonus_week_id FOREIGN KEY (week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE,
  CONSTRAINT fk_weekly_bonus_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS month_summaries (
  month_key TEXT PRIMARY KEY,
  week_ids TEXT,
  closed_at TEXT,
  created_at TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS month_adjustments (
  month_key TEXT,
  class_name TEXT,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  reason TEXT,
  created_at TEXT,
  updated_at TEXT,
  PRIMARY KEY (month_key, class_name),
  CONSTRAINT fk_month_adjustments_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS month_scores (
  month_key TEXT,
  class_name TEXT,
  grade INTEGER,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  total_score DOUBLE PRECISION,
  rank INTEGER,
  note TEXT,
  updated_at TEXT,
  PRIMARY KEY (month_key, class_name),
  CONSTRAINT fk_month_scores_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS semester_summaries (
  semester_key TEXT PRIMARY KEY,
  week_ids TEXT,
  closed_at TEXT,
  created_at TEXT,
  updated_at TEXT,
  month_keys TEXT
);

CREATE TABLE IF NOT EXISTS semester_adjustments (
  semester_key TEXT,
  class_name TEXT,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  reason TEXT,
  created_at TEXT,
  updated_at TEXT,
  PRIMARY KEY (semester_key, class_name),
  CONSTRAINT fk_semester_adjustments_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS semester_scores (
  semester_key TEXT,
  class_name TEXT,
  grade INTEGER,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  total_score DOUBLE PRECISION,
  rank INTEGER,
  note TEXT,
  updated_at TEXT,
  PRIMARY KEY (semester_key, class_name),
  CONSTRAINT fk_semester_scores_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS year_summaries (
  year_key TEXT PRIMARY KEY,
  week_ids TEXT,
  closed_at TEXT,
  created_at TEXT,
  updated_at TEXT,
  semester_keys TEXT
);

CREATE TABLE IF NOT EXISTS year_adjustments (
  year_key TEXT,
  class_name TEXT,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  reason TEXT,
  created_at TEXT,
  updated_at TEXT,
  PRIMARY KEY (year_key, class_name),
  CONSTRAINT fk_year_adjustments_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS year_scores (
  year_key TEXT,
  class_name TEXT,
  grade INTEGER,
  plus_points DOUBLE PRECISION,
  minus_points DOUBLE PRECISION,
  total_score DOUBLE PRECISION,
  rank INTEGER,
  note TEXT,
  updated_at TEXT,
  PRIMARY KEY (year_key, class_name),
  CONSTRAINT fk_year_scores_class_name FOREIGN KEY (class_name) REFERENCES classes(name) ON DELETE CASCADE
);

ALTER TABLE accounts ADD COLUMN IF NOT EXISTS password_changed INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS password_changed_gvcn INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS password_changed_ban_can_su INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS password_changed_codo INTEGER DEFAULT 0;

ALTER TABLE daily_bonus ADD COLUMN IF NOT EXISTS min_score DOUBLE PRECISION;
ALTER TABLE daily_bonus ADD COLUMN IF NOT EXISTS all_above_9 INTEGER;
ALTER TABLE daily_bonus ADD COLUMN IF NOT EXISTS session_id INTEGER;
ALTER TABLE daily_bonus ADD COLUMN IF NOT EXISTS periods_json TEXT;
ALTER TABLE weekly_scores ALTER COLUMN score TYPE DOUBLE PRECISION USING score::double precision;

ALTER TABLE semester_summaries ADD COLUMN IF NOT EXISTS month_keys TEXT;
ALTER TABLE year_summaries ADD COLUMN IF NOT EXISTS semester_keys TEXT;
ALTER TABLE duty_sessions ADD COLUMN IF NOT EXISTS signed_snapshot_hash TEXT;
ALTER TABLE schedule_weeks ADD COLUMN IF NOT EXISTS month_id INTEGER;

DROP INDEX IF EXISTS idx_support_tickets_admin_list;
ALTER TABLE support_tickets DROP CONSTRAINT IF EXISTS support_tickets_status_check;
ALTER TABLE support_tickets DROP CONSTRAINT IF EXISTS support_tickets_priority_check;
ALTER TABLE support_tickets DROP CONSTRAINT IF EXISTS chk_support_ticket_status;
ALTER TABLE support_tickets DROP COLUMN IF EXISTS priority;
ALTER TABLE support_tickets DROP COLUMN IF EXISTS closed_at;
UPDATE support_tickets
SET status = CASE WHEN status IN ('new', 'in_progress') THEN 'in_progress' ELSE 'resolved' END;
ALTER TABLE support_tickets ALTER COLUMN status SET DEFAULT 'in_progress';
ALTER TABLE support_tickets ADD CONSTRAINT chk_support_ticket_status CHECK (status IN ('in_progress', 'resolved'));

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chk_semester_number'
  ) THEN
    ALTER TABLE semesters
    DROP CONSTRAINT chk_semester_number;
  END IF;

  ALTER TABLE semesters
  ADD CONSTRAINT chk_semester_number
  CHECK (semester_number BETWEEN 1 AND 9);
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_schedule_weeks_month_id'
  ) THEN
    ALTER TABLE schedule_weeks
    ADD CONSTRAINT fk_schedule_weeks_month_id
    FOREIGN KEY (month_id) REFERENCES months(id) ON DELETE RESTRICT;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_duty_sessions_week_date_red ON duty_sessions(week_id, date, red_class);
CREATE INDEX IF NOT EXISTS idx_semesters_school_year ON semesters(school_year_id);
CREATE INDEX IF NOT EXISTS idx_months_semester ON months(semester_id);
CREATE INDEX IF NOT EXISTS idx_schedule_weeks_month ON schedule_weeks(month_id);
CREATE INDEX IF NOT EXISTS idx_schedule_assignments_week ON schedule_assignments(week_id);
CREATE INDEX IF NOT EXISTS idx_duty_sessions_week_date ON duty_sessions(week_id, date);
CREATE INDEX IF NOT EXISTS idx_duty_sessions_red ON duty_sessions(red_class);
CREATE INDEX IF NOT EXISTS idx_duty_sessions_duty ON duty_sessions(duty_class);
CREATE INDEX IF NOT EXISTS idx_duty_violations_session ON duty_violations(session_id);
CREATE INDEX IF NOT EXISTS idx_duty_violations_rule ON duty_violations(rule_id);
CREATE INDEX IF NOT EXISTS idx_duty_signatures_session ON duty_signatures(session_id);
CREATE INDEX IF NOT EXISTS idx_duty_revision_logs_session ON duty_revision_logs(session_id);
CREATE INDEX IF NOT EXISTS idx_daily_bonus_session ON daily_bonus(session_id);
CREATE INDEX IF NOT EXISTS idx_bonus_uploads_week_grade ON bonus_uploads(week_id, grade);
CREATE INDEX IF NOT EXISTS idx_absence_evidences_class_week ON absence_evidences(class_id, week_id, submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_absence_evidences_status ON absence_evidences(status, submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_absence_evidence_files_evidence ON absence_evidence_files(evidence_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_absence_exemption_logs_violation ON absence_exemption_logs(duty_violation_id);
CREATE INDEX IF NOT EXISTS idx_absence_exemption_logs_evidence ON absence_exemption_logs(evidence_id);
CREATE INDEX IF NOT EXISTS idx_timetable_entries ON timetable_entries(timetable_id, class_name, day_of_week, session, period);
CREATE INDEX IF NOT EXISTS idx_support_tickets_creator ON support_tickets(creator_role, creator_class_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_tickets_admin_list ON support_tickets(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_messages_ticket ON support_messages(ticket_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_support_attachments_message ON support_attachments(message_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_support_notifications_recipient ON support_notifications(recipient_role, recipient_class_id, is_read, created_at DESC);
